# Generated by Django 4.2.3 on 2023-07-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Project_1',
        ),
    ]
