# Generated by Django 4.2.3 on 2023-07-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_project_project_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_1',
            name='time',
            field=models.DateField(),
        ),
    ]
